public enum ListOfReports
{
    ReportTransactionDetail,
    ReportLabaRugi,
    ReportSalesFactur,
    ReportTransactionByPIC,
    ReportTransactionInternalByPIC,
    ReportTransactionByItem,
    ReportTransactionInternalByItem,
    ReportPiHutangDue,
    ReportPajak,
    ReportStokItem,
    ReportNeraca,
    ReportPiHutangDetail,
    ReportCommission,
    ReportTJournal,
    ReportStokCard,
    ReportJournal,
    ReportChartSalesMonthly,
    ReportDelivery,
    ReportMCustomer,
    ReportMSupplier,
    ReportMEkspedission
}
