--
-- Definition for view V_TOTAL_TRANSACTION_DETAIL : 
--
CREATE VIEW dbo.V_TOTAL_TRANSACTION_DETAIL
AS
SELECT     dbo.T_TRANSACTION.TRANSACTION_ID, dbo.T_TRANSACTION.TRANSACTION_REFERENCE_ID, dbo.T_TRANSACTION.TRANSACTION_FACTUR, 
                      dbo.T_TRANSACTION.TRANSACTION_BY, dbo.T_TRANSACTION.TRANSACTION_DATE, dbo.T_TRANSACTION.TRANSACTION_SUB_TOTAL, 
                      dbo.T_TRANSACTION.TRANSACTION_DISC, dbo.T_TRANSACTION.TRANSACTION_PPN, dbo.T_TRANSACTION.TRANSACTION_GRAND_TOTAL, 
                      dbo.T_TRANSACTION.TRANSACTION_PAID, dbo.T_TRANSACTION.TRANSACTION_SISA, dbo.T_TRANSACTION.TRANSACTION_STATUS, 
                      dbo.T_TRANSACTION.TRANSACTION_DESK, dbo.T_TRANSACTION.EMPLOYEE_ID, ISNULL(dbo.T_TRANSACTION_DETAIL.ITEM_ID, '') AS ITEM_ID, 
                      ISNULL(dbo.T_TRANSACTION_DETAIL.QUANTITY, 0) AS QUANTITY, ISNULL(dbo.T_TRANSACTION_DETAIL.PRICE, 0) AS PRICE, 
                      ISNULL(dbo.T_TRANSACTION_DETAIL.JUMLAH, 0) AS JUMLAH, ISNULL(dbo.T_TRANSACTION_DETAIL.DISC, 0) AS DISC, 
                      ISNULL(dbo.T_TRANSACTION_DETAIL.PPN, 0) AS PPN, ISNULL(dbo.T_TRANSACTION_DETAIL.TOTAL, 0) AS TOTAL, 
                      ISNULL(dbo.T_TRANSACTION_DETAIL.DESCRIPTION, '') AS DESCRIPTION, ISNULL(dbo.T_TRANSACTION_DETAIL.MODIFIED_BY, '') AS MODIFIED_BY, 
                      ISNULL(dbo.T_TRANSACTION_DETAIL.MODIFIED_DATE, GETDATE()) AS MODIFIED_DATE, ISNULL(dbo.M_ITEM.ITEM_NAME, 
                      ISNULL(dbo.T_TRANSACTION_DETAIL.ITEM_ID, '')) AS ITEM_NAME, ISNULL(dbo.M_GROUP.GROUP_NAME, '') AS GROUP_NAME, 
                      ISNULL(dbo.T_TRANSACTION_DETAIL.TRANSACTION_DETAIL_ID, 0) AS TRANSACTION_DETAIL_ID
FROM         dbo.M_GROUP RIGHT OUTER JOIN
                      dbo.M_ITEM ON dbo.M_GROUP.GROUP_ID = dbo.M_ITEM.GROUP_ID RIGHT OUTER JOIN
                      dbo.T_TRANSACTION_DETAIL ON dbo.M_ITEM.ITEM_ID = dbo.T_TRANSACTION_DETAIL.ITEM_ID RIGHT OUTER JOIN
                      dbo.T_TRANSACTION ON dbo.T_TRANSACTION_DETAIL.TRANSACTION_ID = dbo.T_TRANSACTION.TRANSACTION_ID
