--
-- Definition for view V_SUPPLIER_DETAIL : 
--

CREATE VIEW dbo.V_SUPPLIER_DETAIL
AS
SELECT     dbo.M_SUPPLIER.*, ISNULL(dbo.M_SUPPLIER_ACCOUNT.BANK_ID, '') AS BANK_ID, ISNULL(dbo.M_SUPPLIER_ACCOUNT.CURRENCY_ID, '') 
                      AS CURRENCY_ID, ISNULL(dbo.M_SUPPLIER_ACCOUNT.SUPPLIER_ACCOUNT_NO, '') AS SUPPLIER_ACCOUNT_NO, 
                      ISNULL(dbo.M_SUPPLIER_ACCOUNT.SUPPLIER_ACCOUNT_NAME, '') AS SUPPLIER_ACCOUNT_NAME
FROM         dbo.M_SUPPLIER LEFT OUTER JOIN
                      dbo.M_SUPPLIER_ACCOUNT ON dbo.M_SUPPLIER.SUPPLIER_ID = dbo.M_SUPPLIER_ACCOUNT.SUPPLIER_ID
