--
-- Definition for view V_TRANSACTION_DETAIL :
--
CREATE VIEW dbo.V_TRANSACTION_DETAIL
AS
SELECT     dbo.T_TRANSACTION_DETAIL.TRANSACTION_DETAIL_ID, dbo.T_TRANSACTION_DETAIL.TRANSACTION_ID, dbo.T_TRANSACTION_DETAIL.ITEM_ID, 
                      dbo.T_TRANSACTION_DETAIL.QUANTITY, dbo.T_TRANSACTION_DETAIL.PRICE, dbo.T_TRANSACTION_DETAIL.JUMLAH, 
                      dbo.T_TRANSACTION_DETAIL.DISC, dbo.T_TRANSACTION_DETAIL.PPN, dbo.T_TRANSACTION_DETAIL.TOTAL, 
                      dbo.T_TRANSACTION_DETAIL.MODIFIED_BY, dbo.T_TRANSACTION_DETAIL.MODIFIED_DATE, ISNULL(dbo.M_ITEM.ITEM_NAME, '') AS ITEM_NAME, 
                      dbo.T_TRANSACTION_DETAIL.DESCRIPTION
FROM         dbo.T_TRANSACTION_DETAIL LEFT OUTER JOIN
                      dbo.M_ITEM ON dbo.T_TRANSACTION_DETAIL.ITEM_ID = dbo.M_ITEM.ITEM_ID
