
--
-- Dropping view V_TRANSACTION_DETAIL : 
--

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[V_TRANSACTION_DETAIL]') AND OBJECTPROPERTY(id, N'IsView') = 1)
  DROP VIEW [dbo].[V_TRANSACTION_DETAIL]
  
--
-- Dropping view V_TOTAL_TRANSACTION_DETAIL : 
--

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[V_TOTAL_TRANSACTION_DETAIL]') AND OBJECTPROPERTY(id, N'IsView') = 1)
  DROP VIEW [dbo].[V_TOTAL_TRANSACTION_DETAIL]

--
-- Dropping view V_ITEM_DETAIL : 
--

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[V_ITEM_DETAIL]') AND OBJECTPROPERTY(id, N'IsView') = 1)
  DROP VIEW [dbo].[V_ITEM_DETAIL]
  
--
-- Dropping view V_SUPPLIER_DETAIL : 
--

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[V_SUPPLIER_DETAIL]') AND OBJECTPROPERTY(id, N'IsView') = 1)
  DROP VIEW [dbo].[V_SUPPLIER_DETAIL]