public enum ListOfReports
{
    MItem,
    MGroup,
    MSupplier,
    MEmployee,
    MDepartment,
    ReportTransactionTotalByItem,
    TransactionDetail,
    UtangDetail,
    ReportPODetailForPrint,
    ReportTransactionTotalByPIC,
    ReportGiro,
    ReportUsageTotalByAlat,
    ReportTransactionPerMonth,
    ReportPOTotalByItem,
    ReportPOTotalByPIC,
    ReportUserLog,
    ReportListTransaction,
    ReportTagihan
}
